create table "public"."sample3" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying,
    "age" numeric,
    "place" character varying
);


alter table "public"."sample3" enable row level security;

create table "public"."sandya" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text
);


alter table "public"."sandya" enable row level security;

CREATE UNIQUE INDEX sample3_pkey ON public.sample3 USING btree (id);

CREATE UNIQUE INDEX sandya_pkey ON public.sandya USING btree (id);

alter table "public"."sample3" add constraint "sample3_pkey" PRIMARY KEY using index "sample3_pkey";

alter table "public"."sandya" add constraint "sandya_pkey" PRIMARY KEY using index "sandya_pkey";

grant delete on table "public"."sample3" to "anon";

grant insert on table "public"."sample3" to "anon";

grant references on table "public"."sample3" to "anon";

grant select on table "public"."sample3" to "anon";

grant trigger on table "public"."sample3" to "anon";

grant truncate on table "public"."sample3" to "anon";

grant update on table "public"."sample3" to "anon";

grant delete on table "public"."sample3" to "authenticated";

grant insert on table "public"."sample3" to "authenticated";

grant references on table "public"."sample3" to "authenticated";

grant select on table "public"."sample3" to "authenticated";

grant trigger on table "public"."sample3" to "authenticated";

grant truncate on table "public"."sample3" to "authenticated";

grant update on table "public"."sample3" to "authenticated";

grant delete on table "public"."sample3" to "service_role";

grant insert on table "public"."sample3" to "service_role";

grant references on table "public"."sample3" to "service_role";

grant select on table "public"."sample3" to "service_role";

grant trigger on table "public"."sample3" to "service_role";

grant truncate on table "public"."sample3" to "service_role";

grant update on table "public"."sample3" to "service_role";

grant delete on table "public"."sandya" to "anon";

grant insert on table "public"."sandya" to "anon";

grant references on table "public"."sandya" to "anon";

grant select on table "public"."sandya" to "anon";

grant trigger on table "public"."sandya" to "anon";

grant truncate on table "public"."sandya" to "anon";

grant update on table "public"."sandya" to "anon";

grant delete on table "public"."sandya" to "authenticated";

grant insert on table "public"."sandya" to "authenticated";

grant references on table "public"."sandya" to "authenticated";

grant select on table "public"."sandya" to "authenticated";

grant trigger on table "public"."sandya" to "authenticated";

grant truncate on table "public"."sandya" to "authenticated";

grant update on table "public"."sandya" to "authenticated";

grant delete on table "public"."sandya" to "service_role";

grant insert on table "public"."sandya" to "service_role";

grant references on table "public"."sandya" to "service_role";

grant select on table "public"."sandya" to "service_role";

grant trigger on table "public"."sandya" to "service_role";

grant truncate on table "public"."sandya" to "service_role";

grant update on table "public"."sandya" to "service_role";


